services:
  - type: web
    name: prometeylabs-web-prod
    branch: main
    runtime: python
    plan: starter
    region: oregon
    preDeployCommand: |
      python manage.py migrate --noinput
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: |
      gunicorn prometey_project.wsgi:application --preload --log-file - --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: "prometey_project.settings"
      - key: PYTHON_VERSION
        value: "3.13.5"
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      # RENDER_EXTERNAL_URL є дефолтною змінною середовища від Render; не визначаємо вручну
      - key: SECURE_SSL_REDIRECT
        value: "True"
      - key: DATABASE_URL
        fromDatabase:
          name: prometeylabs-db-prod
          property: connectionString
      - key: SITE_URL
        sync: false
      - key: MONOBANK_TOKEN
        sync: false
    autoDeploy: true

databases:
  - name: prometeylabs-db-prod
    plan: starter
    region: oregon
    postgresVersion: "16"

